using System.Linq;
using Content.Client.DoAfter;
using Content.Client.UserInterface.Controls;
using Content.Shared.Power.Generator;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Client.UserInterface.Controls;
using Robust.Shared.Network;

namespace Content.Client._NF.Power;

[GenerateTypedNameReferences]
public sealed partial class StationaryGeneratorWindow : FancyWindow
{
    [Dependency] private readonly IEntityManager _entityManager = default!;

    private EntityUid _entity;

    public float? MaximumPower;

    public event Action<float>? OnPower;
    public event Action<bool>? OnState;
    public event Action? OnSwitchOutput;
    public event Action? OnEjectFuel;

    public StationaryGeneratorWindow()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        TargetPower.IsValid += IsValid;
        TargetPower.OnValueChanged += (args) =>
        {
            OnPower?.Invoke(args.Value);
        };

        StartButton.OnPressed += _ => OnState?.Invoke(true);
        StopButton.OnPressed += _ => OnState?.Invoke(false);
        OutputSwitchButton.OnPressed += _ => OnSwitchOutput?.Invoke();
        FuelEject.OnPressed += _ => OnEjectFuel?.Invoke();
    }

    public void SetEntity(EntityUid entity)
    {
        _entity = entity;
        EntityView.SetEntity(entity);
    }

    private bool IsValid(float arg)
    {
        if (!float.IsFinite(arg) || arg < 0)
            return false;

        if (arg > (MaximumPower / 1000.0f ?? 0))
            return false;

        return true;
    }

    public void Update(PortableGeneratorComponentBuiState state)
    {
        MaximumPower = state.MaximumPower;
        AtmosPanel.Visible = BoilerPanel.Visible = RpmRow.Visible = WarningsPanel.Visible = DrivePanel.Visible = false;
        if (state.Stationary is { } data)
        {
            OxygenUseRow.Visible = OxygenStatusRow.Visible = data.OxygenMoles.HasValue;
            ExhaustOutputRow.Visible = ExhaustStatusRow.Visible = data.HasExhaust;
            AtmosPanel.Visible = data.OxygenMoles.HasValue || data.HasExhaust;
            BoilerPanel.Visible = data.BoilerTemperature.HasValue;
            RpmRow.Visible = data.Rpm.HasValue;
            WarningsPanel.Visible = data.Warnings.Count > 0;
            FuelUseRow.Visible = FuelLeftRow.Visible = data.FuelKind != "uninstalled";
            FuelType.Text = Loc.GetString($"stationary-ui-fuel-type-{data.FuelKind}");
            FuelUse.Text = $"{data.FuelRate:0.###} {FuelUnit(data.FuelKind)}/s";
            SetStatus(FuelStatus, data.FuelState, "supply");
            OxygenUse.Text = $"{data.OxygenRate:0.###} mol/s";
            SetStatus(OxygenStatus, data.OxygenState, "atmos");
            OxygenStatus.ToolTip = Loc.GetString("stationary-ui-oxygen-available", ("amount", data.OxygenMoles ?? 0f));
            ExhaustOutput.Text = $"{data.ExhaustRate:0.###} mol/s";
            SetStatus(ExhaustStatus, data.ExhaustState, "atmos");
            ExhaustStatus.ToolTip = data.ExhaustPressure is { } pressure
                ? Loc.GetString("stationary-ui-exhaust-pressure", ("pressure", pressure)) : null;
            BoilerTemperature.Text = data.BoilerTemperature is { } temperature ? $"{temperature - 273.15f:0.0} °C" : "—";
            BoilerPressure.Text = data.BoilerPressure is { } boilerPressure ? $"{boilerPressure:0} kPa" : "—";
            SetStatus(BoilerStatus, data.BoilerState, "boiler");
            WaterUse.Text = $"{data.WaterRate:0.###} u/s";
            Water.Text = $"{data.Water:0.##} / {data.WaterCapacity:0.##} u";
            SetStatus(WaterStatus, data.WaterState, "supply");
            Rpm.Text = $"{data.Rpm:0} / {data.RatedRpm:0} RPM";
            Rpm.ToolTip = Loc.GetString("stationary-ui-shaft-help");
            CurrentOutput.Text = $"{data.CurrentPower / 1000f:0.00} / {state.MaximumPower / 1000f:0.##} kW";
            AverageOutput.Text = $"{data.AveragePower / 1000f:0.00} kW/m";
            AverageOutput.ToolTip = Loc.GetString("stationary-ui-average-help");
            ElectricalLoad.Text = data.ElectricalLoad.ToString("P1");
            ElectricalLoad.ToolTip = Loc.GetString("stationary-ui-electrical-load-help");
            RampRate.Text = $"{data.RampRate / 1000f:0.##} kW/s";
            SetStatus(GeneratorStatus, data.GeneratorState, "machine");
            Safety.Text = string.Join("\n", data.Warnings.Select(warning => $"• {Loc.GetString($"stationary-ui-safety-{warning}")}"));
            DrivePanel.Visible = data.Rpm.HasValue && data.DriveTemperature.HasValue;
            DriveHeading.Text = Loc.GetString($"stationary-ui-{data.DriveKind}-panel");
            DriveRpmLabel.Text = Loc.GetString($"stationary-ui-{data.DriveKind}-rpm");
            DriveTemperatureLabel.Text = Loc.GetString($"stationary-ui-{data.DriveKind}-temperature");
            DriveLoadLabel.Text = Loc.GetString($"stationary-ui-{data.DriveKind}-load");
            DriveStatusLabel.Text = Loc.GetString($"stationary-ui-{data.DriveKind}-status");
            DriveRpm.Text = $"{data.Rpm:0} RPM";
            DriveTemperature.Text = $"{data.DriveTemperature - 273.15f:0.0} °C";
            DriveTemperature.ToolTip = Loc.GetString("stationary-ui-drive-temperature-help");
            DriveLoad.Text = data.MechanicalLoad.ToString("P1");
            DriveLoad.ToolTip = Loc.GetString("stationary-ui-mechanical-load-help");
            SetStatus(DriveStatus, data.DriveState, "machine");
        }

        if (!_entityManager.TryGetComponent(_entity, out FuelGeneratorComponent? component))
            return;

        if (!TargetPower.HasKeyboardFocus())
            TargetPower.Value = state.TargetPower / 1000.0f; // Frontier: retain fractional kW
        var efficiency = SharedGeneratorSystem.CalcFuelEfficiency(state.TargetPower, state.OptimalPower, component);
        Efficiency.Text = float.IsFinite(efficiency) ? efficiency.ToString("P1") : "—";

        var burnRate = state.FuelBurnRate / efficiency;
        var left = state.RemainingFuel / burnRate;

        Eta.Text = float.IsFinite(left) && burnRate > 0f
            ? Loc.GetString("portable-generator-ui-eta", ("minutes", Math.Ceiling(left / 60.0))) : "";
        Eta.ToolTip = Loc.GetString("stationary-ui-eta-help");
        if (state.Stationary is { } fuelData)
        {
            var unit = FuelUnit(fuelData.FuelKind);
            FuelLeft.Text = fuelData.FuelCapacity is { } capacity
                ? $"{fuelData.FuelQuantity:0.##} / {capacity:0.##} {unit}"
                : $"{fuelData.FuelQuantity:0.##} {unit}";
            FuelEject.Visible = fuelData.FuelKind is "liquid" or "solid";
        }
        TargetPower.ToolTip = Loc.GetString("stationary-generator-maximum-target", ("power", state.MaximumPower / 1000f));

        var progress = 0f;

        var unanchored = !_entityManager.GetComponent<TransformComponent>(_entity).Anchored;
        var starting = !unanchored && TryGetStartProgress(out progress);
        var on = !unanchored && !starting && state.On;
        var off = !unanchored && !starting && !state.On;

        LabelUnanchored.Visible = unanchored;
        StartProgress.Visible = starting;
        StopButton.Visible = on;
        StartButton.Visible = off;

        var coasting = !state.On && state.Stationary?.Rpm > 0f;
        SetStatus(StatusLabel, starting ? "starting" : on ? "running" : coasting ? "stopping" : "off", "control");
        if (starting)
            StartProgress.Value = progress;

        var canSwitch = _entityManager.TryGetComponent(_entity, out PowerSwitchableComponent? switchable);
        var switcher = _entityManager.System<SharedPowerSwitchableSystem>();
        OutputSwitchRow.Visible = canSwitch;
        OutputSwitchLabel.Visible = canSwitch;
        OutputSwitchButton.Visible = canSwitch;

        if (switchable != null)
        {
            var voltage = switcher.VoltageString(switcher.GetVoltage(_entity, switchable));
            OutputVoltage.Text = voltage;
            OutputVoltage.FontColorOverride = voltage == "HV" ? Color.Orange : Color.Yellow;
            var nextVoltage = switcher.VoltageString(switcher.GetNextVoltage(_entity, switchable));
            OutputSwitchButton.Text = Loc.GetString("power-switchable-switch-voltage", ("voltage", nextVoltage));
            OutputSwitchButton.Disabled = state.On;
        }


        if (state.NetworkStats is { } netStats)
        {
            NetworkStats.Text = $"{(state.Stationary?.CurrentPower ?? 0f) / 1000f:0.00} / {netStats.Load / 1000f:0.00} kW";
            NetworkStats.ToolTip = Loc.GetString("stationary-ui-network-load-help");
            SetStatus(NetworkStatus, NetworkState(netStats.Load, netStats.Supply), "network");
            NetworkStatus.ToolTip = Loc.GetString("stationary-ui-network-supply-help", ("supply", netStats.Supply / 1000f));
        }
        else
        {
            NetworkStats.Text = "—";
            NetworkStats.ToolTip = null;
            SetStatus(NetworkStatus, "off", "network");
            NetworkStatus.ToolTip = null;
        }
    }

    public static string NetworkState(float demand, float supply) =>
        supply < demand ? "danger" : demand > 0f && supply < demand * 1.1f ? "warning" : "normal";

    private static void SetStatus(Label label, string state, string group)
    {
        label.Text = Loc.GetString($"stationary-ui-{group}-{state}");
        label.FontColorOverride = state == "off" ? Color.Gray : null;
        label.SetOnlyStyleClass(state switch
        {
            "normal" or "operational" or "running" => "Good",
            "warning" or "heating" or "cooling" or "starting" or "stopping" => "Caution",
            "danger" or "cold" => "Danger",
            _ => ""
        });
    }

    private static string FuelUnit(string kind) => kind switch
    {
        "liquid" => "u",
        "gas" => "mol",
        "solid" => Loc.GetString("stationary-ui-material-units"),
        _ => ""
    };

    private bool TryGetStartProgress(out float progress)
    {
        // Try to check progress of auto-revving first
        if (_entityManager.TryGetComponent<ActiveGeneratorRevvingComponent>(_entity, out var activeGeneratorRevvingComponent) && _entityManager.TryGetComponent<PortableGeneratorComponent>(_entity, out var portableGeneratorComponent))
        {
            var calculatedProgress = activeGeneratorRevvingComponent.CurrentTime / portableGeneratorComponent.StartTime;
            progress = (float) calculatedProgress;
            return true;
        }

        var doAfterSystem = _entityManager.EntitySysManager.GetEntitySystem<DoAfterSystem>();
        return doAfterSystem.TryFindActiveDoAfter<GeneratorStartedEvent>(_entity, out _, out _, out progress);
    }
}


